name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Make your code available
      - uses: actions/checkout@v3

      # 2) Python setup
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3) Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4) Check for requirements.txt and set a flag
      - name: Check for requirements.txt
        id: req-file
        run: |
          if [ -f "./requirements.txt" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 5) Conditionally install dependencies
      - name: Install dependencies
        if: steps.req-file.outputs.exists == 'true'
        run: pip install -r requirements.txt

      # 6) Optional: log that we skipped
      - name: Skip notice
        if: steps.req-file.outputs.exists == 'false'
        run: echo "› requirements.txt not found — dependency install skipped"

      # 7) Your other build/test steps go here
      - name: Run tests
        run: |
          echo "→ run your tests here"
